package org.andrei.sample_project;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import org.andrei.sample_project.model.Person;
import org.andrei.sample_project.repository.PersonRepository;

public class HelloController {
    // buttons
    @FXML
    private Button createButton;
    @FXML
    private Button editButton;
    @FXML
    private Button deleteButton;

    // inputs
    @FXML
    private TextField firstNameInput;

    @FXML
    private TextField lastNameInput;

    @FXML
    private TextField ageInput;

    @FXML
    private TableView<Person> table;

    private ObservableList<Person> personList;

    private PersonRepository personRepository;

    @FXML
    public void initialize() {
        // Initialize the table and columns
        addTableColumns();

        personRepository = new PersonRepository();
        personList = FXCollections.observableArrayList(
                personRepository.getAllPersons()
        );

        // Bind the person list to the table
        table.setItems(personList);

        // Add listener to update text fields when a row is selected
        table.getSelectionModel().selectedItemProperty().addListener((observable, oldValue, newValue) -> {
            if (newValue != null) {
                // If a person is selected, populate the text fields
                firstNameInput.setText(newValue.getFirstName());
                lastNameInput.setText(newValue.getLastName());
                ageInput.setText(String.valueOf(newValue.getAge()));
            }
        });
    }

    @FXML
    protected void onCreate() {
        String firstName = firstNameInput.getText();
        String lastName = lastNameInput.getText();
        int age = Integer.parseInt(ageInput.getText());  // Convert age to int

        // ID will be generated by the database
        Person newPerson = new Person(null, firstName, lastName, age);

        // Add person to the list and table (simulate saving to database here)
        newPerson = personRepository.createPerson(newPerson); // Assume createPerson returns the updated object with ID
        personList.add(newPerson);  // Add to table data
        System.out.println("Person created: " + newPerson.getFirstName() + " " + newPerson.getLastName() + ", Age: " + newPerson.getAge());
    }

    @FXML
    protected void onEdit() {
        // Get the selected person from the table
        Person selectedPerson = table.getSelectionModel().getSelectedItem();

        if (selectedPerson != null) {
            // Update the selected person's details based on user input
            selectedPerson.setFirstName(firstNameInput.getText());
            selectedPerson.setLastName(lastNameInput.getText());
            selectedPerson.setAge(Integer.parseInt(ageInput.getText()));

            // Save updated person to database (simulated here)
            personRepository.editPerson(selectedPerson);

            // Refresh the table
            table.refresh();
            System.out.println("Person edited: " + selectedPerson.getFirstName() + " " + selectedPerson.getLastName() + ", Age: " + selectedPerson.getAge());
        } else {
            // Show an alert if no person is selected
            showAlert("No Selection", "Please select a person to edit.");
        }
    }

    @FXML
    protected void onDelete() {
        // Get the selected person from the table
        Person selectedPerson = table.getSelectionModel().getSelectedItem();

        if (selectedPerson != null) {
            // Remove the selected person from the table (and simulate deleting from the database)
            boolean deleted = personRepository.deletePerson(selectedPerson);
            if (deleted) {
                personList.remove(selectedPerson);  // Remove from table data
                System.out.println("Person deleted: " + selectedPerson.getFirstName() + " " + selectedPerson.getLastName());
            }
        } else {
            // Show an alert if no person is selected
            showAlert("No Selection", "Please select a person to delete.");
        }
    }

    private void addTableColumns() {
        // First Name column
        TableColumn<Person, String> firstNameColumn = new TableColumn<>("First Name");
        firstNameColumn.setCellValueFactory(new PropertyValueFactory<>("firstName"));

        // Last Name column
        TableColumn<Person, String> lastNameColumn = new TableColumn<>("Last Name");
        lastNameColumn.setCellValueFactory(new PropertyValueFactory<>("lastName"));

        // Age column
        TableColumn<Person, Integer> ageColumn = new TableColumn<>("Age");
        ageColumn.setCellValueFactory(new PropertyValueFactory<>("age"));

        // Add columns to the table
        table.getColumns().add(firstNameColumn);
        table.getColumns().add(lastNameColumn);
        table.getColumns().add(ageColumn);
    }

    // Helper method to show alerts
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.WARNING);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}
